---
title: "Data analysis for the vision impaired"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE, include=FALSE}
library("tidyverse")
library("kableExtra")
set.seed(123)  
theme_touch <- theme(axis.title.y = element_text(size=rel(1.8),
                                margin = margin(t=0, r=.5, b=0, l=0, "cm")),
                     axis.title.x = element_text(size=rel(1.8),
                                margin = margin(t=.5, r=0, b=0, l=0, "cm")),
                     axis.text = element_text(size=rel(1.6)),
                     plot.margin = margin(2, 2, 2, 2, "cm"))
out.w <- 20
out.h <- 11
```

```{r simple_categ, echo=FALSE, include=FALSE}
employ.s <- tribble(
  ~Employment,
  #--
  "Unemployed",
  "Unemployed",
  "Part time",
  "Part time",
  "Part time",
  "Full time",
  "Full time",
  "Full time",
  "Full time",
)
```
<br />
<br />

# A table of categorical data
<br />
```{r, echo=FALSE}
knitr::kable(
  employ.s,
) %>% kable_styling(full_width = F, font_size = 24)
```
<br />
<br />

# A table of counts for the same data
<br />
```{r, echo=FALSE}
knitr::kable(
  count(employ.s, Employment),
) %>% kable_styling(full_width = F, font_size = 24)
```
<br />
<br />

# A bar plot of the same data
<br />
```{r simple_categ_show, echo=FALSE}
ggplot(employ.s, aes(Employment)) +
  geom_bar(color="black", fill="black", width=0.5) +
  theme_touch
```
<br />
<br />

```{r, echo=FALSE, include=FALSE}
v <- rnorm(500, mean=52.5, sd=7)
df <- data.frame(Age = v)
```


# A histogram of 500 ages in years
<br />
```{r, echo=FALSE}
ggplot(df, aes(Age)) +
  geom_bar(color="black", fill="black", width=0.5) + 
  scale_x_binned() + 
  theme_touch
```
<br />
<br />





<!-- End -->